# Google Cloud Build configuration for ClinicConnect
# Deploy to Cloud Run with external database (Neon PostgreSQL)
#
# Usage:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_DATABASE_URL="your-database-url"
#
# Or set up secrets in Secret Manager first, then:
#   gcloud builds submit --config cloudbuild.yaml

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: clinicconnect
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _MEMORY: 1Gi
  _CPU: "1"
  _CONCURRENCY: "80"
  # These can be overridden via --substitutions flag
  _DATABASE_URL: ""
  _SESSION_SECRET: ""

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_8

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      # Resources
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      # Request timeout
      - '--timeout'
      - '300s'
      # Startup CPU boost for faster cold starts
      - '--cpu-boost'
      # Port configuration
      - '--port'
      - '8080'
      # Environment variables (DATABASE_URL and SESSION_SECRET passed directly)
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080,SKIP_MIGRATIONS=true,DATABASE_URL=${_DATABASE_URL},SESSION_SECRET=${_SESSION_SECRET}'
      # Allow unauthenticated access (public API)
      - '--allow-unauthenticated'
    id: 'deploy'
    waitFor: ['push-image']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build timeout (15 minutes)
timeout: '900s'

