# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml

name: clinicconnect
region: nyc

# ============================================
# Services
# ============================================
services:
  - name: web
    # Build from Dockerfile
    dockerfile_path: Dockerfile.optimized
    
    # Or use pre-built image from registry
    # image:
    #   registry_type: DOCR
    #   repository: clinicconnect
    #   tag: latest
    
    # GitHub repository
    github:
      repo: lacson1/clinicconnect-2
      branch: main
      deploy_on_push: true
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo, upgrade as needed
    
    # HTTP settings
    http_port: 5001
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      # REQUIRED: Security secrets (generate with: openssl rand -base64 32)
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
      # Optional: AI Keys
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""
      # Optional: Email
      - key: SENDGRID_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""
    
    # Routes
    routes:
      - path: /

# ============================================
# Database
# ============================================
databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database  # Free dev database, or db-s-1vcpu-1gb for production ($15/mo)
    num_nodes: 1

# ============================================
# Alerts (Optional)
# ============================================
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# ============================================
# Ingress (Domain Configuration)
# ============================================
# ingress:
#   rules:
#     - component:
#         name: web
#       match:
#         path:
#           prefix: /
#       cors:
#         allow_origins:
#           - exact: "https://your-domain.com"
#         allow_methods:
#           - GET
#           - POST
#           - PUT
#           - DELETE
#           - OPTIONS
#         allow_headers:
#           - Content-Type
#           - Authorization
#         max_age: "86400"

